export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-surface": "#1a1c1c",
              "on-error-container": "#93000a",
              "surface-container": "#eeeeee",
              "on-secondary-container": "#646464",
              "on-tertiary-fixed-variant": "#464747",
              "secondary": "#5e5e5e",
              "surface-bright": "#f9f9f9",
              "on-surface-variant": "#5a4136",
              "on-primary-container": "#572000",
              "primary": "#a04100",
              "inverse-on-surface": "#f1f1f1",
              "primary-container": "#ff6b00",
              "surface": "#f9f9f9",
              "inverse-primary": "#ffb693",
              "on-background": "#1a1c1c",
              "on-error": "#ffffff",
              "outline-variant": "#e2bfb0",
              "surface-container-high": "#e8e8e8",
              "on-primary-fixed-variant": "#7a3000",
              "on-primary": "#ffffff",
              "tertiary-fixed-dim": "#c7c6c6",
              "outline": "#8e7164",
              "tertiary-fixed": "#e3e2e2",
              "on-secondary-fixed-variant": "#474747",
              "error-container": "#ffdad6",
              "background": "#f9f9f9",
              "surface-dim": "#dadada",
              "inverse-surface": "#2f3131",
              "tertiary-container": "#999999",
              "on-tertiary-container": "#303132",
              "primary-fixed": "#ffdbcc",
              "surface-container-low": "#f3f3f3",
              "primary-fixed-dim": "#ffb693",
              "on-secondary": "#ffffff",
              "surface-tint": "#a04100",
              "surface-container-highest": "#e2e2e2",
              "tertiary": "#5e5e5f",
              "secondary-fixed": "#e2e2e2",
              "on-tertiary-fixed": "#1a1c1c",
              "surface-variant": "#e2e2e2",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed-dim": "#c6c6c6",
              "on-tertiary": "#ffffff",
              "on-primary-fixed": "#351000",
              "on-secondary-fixed": "#1b1b1b",
              "error": "#ba1a1a",
              "secondary-container": "#e2e2e2"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "4px",
              "margin-desktop": "48px",
              "xs": "4px",
              "sm": "8px",
              "lg": "24px",
              "gutter": "16px",
              "md": "16px",
              "margin-mobile": "16px",
              "xl": "32px"
      },
      "fontFamily": {
              "headline-md": ["Inter"],
              "label-md": ["Inter"],
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "label-sm": ["Inter"],
              "body-md": ["Inter"],
              "headline-xl": ["Inter"],
              "headline-lg-mobile": ["Inter"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
